### ISSUE TITLE
NGA Followup

### ISSUE THREAD

**Issue by DanRunfola** [itpir/AidDataLabs#17]
Seth -

I owe the NGA a response to the below email.  At your earliest convenience, could you send an email to the SciClone folk and find out what level of security we can provide for data (...for free, based on the resources we've already committed)?

Once you've done that, if you could send me a one-paragraph email I can use to respond to the below request.  For now just ask for myself and you to have data to keep it simple; we can ask for expansion later if warranted / needed.

-----------------------------------------------------------------------

Classification: UNCLASSIFIED
======================================================

Please note I am still waiting for Dan Runfola, the Chief Geospatial Scientist for AidData under the USAID award, to explain where the imagery will be housed and who will have access to it. Once I receive that information I can continue processing the request for access.

**Comment by sgoodm** [comment]
done a while back, closing this out
