### ISSUE TITLE
Mean Surface Rasters - aid raster calculation scripts (generalized for eventual integration with DET).

### ISSUE THREAD

**Issue by DanRunfola** [itpir/AidDataLabs#20]
This script will produce a raster for a given query against an AidData geocoded dataset, where each cell represents the mean estimated dollars of aid.

This data will be used in a number of other scripts.

This task is to make a generalizeable version of this script, so that it can (eventually) be used in conjunction with the DET.

**Comment by sgoodm** [comment]
core functions complete. needs to be operationalized

**Comment by sgoodm** [comment]
still need to:  
- finalize input (msr request) and output (for adding to asdf) procedures
- write full filter functions (currently just takes single string for sector match)

**Comment by sgoodm** [comment]
updated to utilize feature codes (in addition to precision codes) to define location geometry. will eventually switch to new iati location class standard

**Comment by sgoodm** [comment]
integration with det-module planned for close beta stage 1 #28

**Comment by sgoodm** [comment]
core det-module integration complete

**Comment by sgoodm** [comment]
closing this out. can create new msr/level2 issues if needed
