### ISSUE TITLE
Script: Uncertainty Extraction Routine

### ISSUE THREAD

**Issue by DanRunfola** [itpir/AidDataLabs#21]
This script will run in the background when a user requests an AidData extraction in the new DET.

It will return a total of three columns of data to the polygon.

The first of these columns is the mean dollar of aid (sum) from the extract.

The second of these columns is the maximum possible dollars of aid, from a intersect search.

The third of these columns is the mean / max, or the average probability that any single dollar falls in the polygon.

Note this needs to be extensible to the project ocunt (all dollar values = 1) case, which will extract from the count raster.

**Comment by sgoodm** [comment]
core functions complete. needs to be operationalized

script combined with #20

**Comment by sgoodm** [comment]
added into det queue processing script. needs testing

**Comment by sgoodm** [comment]
tested integrated reliability calcs with det-module and everything works
