### ISSUE TITLE
HPC - Moving the ball on AidData @ SciClone

### ISSUE THREAD

**Issue by DanRunfola** [itpir/AidDataLabs#24]
1) 2 new accounts (datateam, reu) that would just be used with the /sciclone/aiddata10 space. we can go through the normal account form process to create them, but i wanted to run it by you first since they would be "organization" accounts and would not be associated with an individual

2) new group (aiddata-admin) for select aiddata10 "admin" accounts (sgoodman, geogdan, wsstewar, datateam, reu)

3) ssh-key access, at least for the datateam account

The 2 new accounts are going to be used for managing /sciclone/aiddata10 and automated I/O tasks. We don't want to use an individual's account since a few people will have access to it and so we don't have to worry about transferring it should someone leave in the future. 

The new "datateam" account (and possibly "reu") are going to be used as part of an automated workflow for reading/writing on aiddata10 which is the main reason for ssh-key access. If it matters, I do not think that these 2 new account would ever need to do anything except read/write on aiddata10.

The new group will help us manage access to aiddata10. "aiddata-admin" will allow full write access on aiddata10 and down the road we will likely need 1 or 2 additional groups which we can give limited write permissions for different tasks (rather than setting permissions on a user by user basis). Right now I am just planning to do this by manually setting directory ACLs as needed but if there is some other method you would prefer us to use I am open to suggestions.

**Comment by sgoodm** [comment]
#26

**Comment by sgoodm** [comment]
root and team directory permissions should be set for existing groups. teams can handle their own subfolder permissions
