### ISSUE TITLE
Global Distance to Roads

### ISSUE THREAD

**Issue by DanRunfola** [itpir/AidDataLabs#9]
Calculate a global distance to Roads raster

**Comment by DanRunfola** [comment]
groads - roads
http://sedac.ciesin.columbia.edu/data/set/groads-global-roads-open-access-v1

**Comment by DanRunfola** [comment]
Being done by student group

**Comment by DanRunfola** [comment]
Files ready, need to pass to Seth for integration on SciClone.

**Comment by sgoodm** [comment]
done
